# Generated by Django 3.2.25 on 2026-04-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0004_deploy_mode_user_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymenttask',
            name='action',
            field=models.CharField(choices=[('precheck', '预检查 (precheck)'), ('precheck_install', '安装前置检查 (precheck install <组件>)'), ('precheck_upgrade', '升级前置检查 (precheck upgrade <组件>)'), ('install', '安装 (install [组件])'), ('upgrade', '升级 (upgrade [组件])'), ('uninstall_all', '卸载 (uninstall_all [组件])'), ('rollback', '回滚 (rollback [组件])'), ('repair', '修复 (repair [组件])')], max_length=32),
        ),
        migrations.AlterField(
            model_name='deploymenttask',
            name='target',
            field=models.CharField(blank=True, default='gaussdb', help_text='precheck install|upgrade 必填组件名；install/upgrade/uninstall_all/rollback/repair 可选填组件', max_length=64),
        ),
        migrations.AlterField(
            model_name='deploymenttask',
            name='user_edit_content',
            field=models.TextField(help_text='将写入远程 user_edit_file.conf（覆盖前会先解析 [user_edit]）', verbose_name='user_edit 配置内容'),
        ),
    ]
