# Generated by Django 3.2.25 on 2026-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('hostname', models.CharField(max_length=255, verbose_name='地址')),
                ('port', models.PositiveIntegerField(default=22, verbose_name='SSH 端口')),
                ('username', models.CharField(max_length=64, verbose_name='SSH 用户')),
                ('auth_method', models.CharField(choices=[('key', '密钥'), ('password', '密码')], default='password', max_length=16)),
                ('credential', models.TextField(blank=True, verbose_name='凭证密文')),
                ('docker_service_root', models.CharField(blank=True, help_text='远程主机上包含 autoChangeInterface 的目录，例如 /opt/docker-service', max_length=512, verbose_name='docker-service 根目录')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
                'ordering': ['-created_at'],
            },
        ),
    ]
