# Generated by Django 3.2.25 on 2026-04-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_host_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='docker_service_root',
            field=models.CharField(blank=True, help_text='远程主机上 appctl.sh 所在目录，例如 /data/docker-service', max_length=512, verbose_name='部署根目录'),
        ),
    ]
