# Generated by Django 3.2.25 on 2026-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_alter_host_deploy_root_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='docker_service_root',
            field=models.CharField(blank=True, help_text='远程 appctl.sh 所在目录（如 /data/docker-service）；manifest 读取 config/gaussdb/manifest.yaml', max_length=512, verbose_name='部署根目录'),
        ),
    ]
